# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171211_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('date', 'times', 'meeting_room')]),
        ),
    ]
