# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171211_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Booking',
        ),
    ]
