# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171211_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='meeting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Meeting_room', verbose_name='会议室'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User', verbose_name='预定人'),
        ),
    ]
